'use strict';

/**
 * Bundles the Electron data layer into a single browser script for the Android
 * app.
 *
 * The point is that there is exactly one copy of the intelligence. Every service,
 * the poller, alerts, attribution, review analysis and the publisher cohort are
 * plain JS that only ever touch global `fetch` — none of them import a Node
 * built-in — so they run unmodified in a WebView. Only three things are actually
 * platform-bound, and each gets a mobile replacement injected under the same
 * module id:
 *
 *   ./atomic          fs read/write   ->  localStorage (still synchronous)
 *   ./services/http   Node fetch      ->  CapacitorHttp (bypasses CORS)
 *   fs / path         Node built-ins  ->  thin shims
 *
 * Everything else is copied verbatim. Change a service on the desktop side and
 * the phone inherits it on the next `npm run mobile:build` — the two cannot
 * drift, because there is nothing to keep in sync.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'mobile', 'www', 'js', 'cultwatch-core.js');

// main.js and preload.js are the Electron shell; the mobile bootstrap replaces
// them. Everything else in electron/ is portable.
const SKIP = new Set(['main.js', 'preload.js']);

function collect() {
  const mods = [];
  for (const f of fs.readdirSync(path.join(ROOT, 'electron')).sort()) {
    if (!f.endsWith('.js') || SKIP.has(f)) continue;
    mods.push({ id: './' + f.replace(/\.js$/, ''), file: path.join(ROOT, 'electron', f) });
  }
  for (const f of fs.readdirSync(path.join(ROOT, 'electron', 'services')).sort()) {
    if (!f.endsWith('.js')) continue;
    mods.push({ id: './services/' + f.replace(/\.js$/, ''), file: path.join(ROOT, 'electron', 'services', f) });
  }
  return mods;
}

function build() {
  const mods = collect();
  const overrides = {
    './atomic': path.join(ROOT, 'mobile', 'platform', 'atomic.js'),
    './services/http': path.join(ROOT, 'mobile', 'platform', 'http.js')
  };

  const parts = [];
  for (const m of mods) {
    const src = fs.readFileSync(overrides[m.id] || m.file, 'utf8');
    parts.push(`  reg(${JSON.stringify(m.id)}, function (module, exports, require) {\n${src}\n  });`);
  }

  const bundle = `'use strict';
/* GENERATED by scripts/build-mobile.js — do not edit.
 * Source of truth is electron/ plus mobile/platform/. Rebuild with:
 *   npm run mobile:build
 */
(function (global) {
  var defs = {}, cache = {};
  function reg(id, fn) { defs[id] = fn; }

  // Module ids are written relative to electron/ ("./config",
  // "./services/steam"), so a require from inside services/ has to be resolved
  // against its own directory before falling back to the flat id.
  function resolve(from, id) {
    if (defs[id]) return id;
    if (id.startsWith('./') && from.startsWith('./services/')) {
      var asService = './services/' + id.slice(2);
      if (defs[asService]) return asService;
    }
    if (id.startsWith('../')) {
      var up = './' + id.slice(3);
      if (defs[up]) return up;
    }
    return id;
  }

  function makeRequire(from) {
    return function (id) {
      var key = resolve(from, id);
      if (SHIMS[key]) return SHIMS[key];
      if (cache[key]) return cache[key].exports;
      var def = defs[key];
      if (!def) throw new Error('cultwatch-core: unknown module "' + id + '" (from ' + from + ')');
      var module = { exports: {} };
      cache[key] = module;
      def(module, module.exports, makeRequire(key));
      return module.exports;
    };
  }

  // --- Node shims -------------------------------------------------------
  // Only the handful of calls the portable modules actually make. Paths become
  // opaque storage keys: nothing on the phone is a real file.
  var SHIMS = {
    path: {
      join: function () { return Array.prototype.slice.call(arguments).filter(Boolean).join('/'); },
      dirname: function (p) { return String(p).split('/').slice(0, -1).join('/') || '.'; },
      basename: function (p) { return String(p).split('/').pop(); }
    },
    fs: {
      // The store calls this before writing; localStorage has no directories.
      mkdirSync: function () {},
      readFileSync: function () { throw new Error('ENOENT'); },
      writeFileSync: function () { throw new Error('unsupported on mobile'); },
      renameSync: function () { throw new Error('unsupported on mobile'); },
      unlinkSync: function () {}
    }
  };

${parts.join('\n\n')}

  global.CultWatchCore = {
    require: makeRequire('./'),
    moduleIds: Object.keys(defs)
  };
})(typeof globalThis !== 'undefined' ? globalThis : window);
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, bundle);
  return { count: mods.length, bytes: Buffer.byteLength(bundle), ids: mods.map((m) => m.id) };
}

// --- Web assets ---------------------------------------------------------
// The three view scripts and the stylesheet are copied verbatim from renderer/.
// They are already framework-free and talk only to `window.cultwatch`, which the
// mobile bootstrap provides under the same names.
const RENDERER_FILES = ['app.js', 'trends.js', 'tinybuild.js', 'styles.css'];

function assets() {
  const www = path.join(ROOT, 'mobile', 'www');
  fs.mkdirSync(www, { recursive: true });

  for (const f of RENDERER_FILES) {
    fs.copyFileSync(path.join(ROOT, 'renderer', f), path.join(www, f));
  }
  fs.copyFileSync(path.join(ROOT, 'mobile', 'platform', 'mobile.css'), path.join(www, 'mobile.css'));

  let html = fs.readFileSync(path.join(ROOT, 'renderer', 'index.html'), 'utf8');

  // Without this the WebView renders the desktop layout at desktop width and
  // then scales it down — everything technically present and nothing readable.
  html = html.replace('</head>',
    '  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />\n' +
    '  <link rel="stylesheet" href="mobile.css" />\n</head>');

  // The core bundle and bootstrap stand in for preload.js, so they must run
  // before any view script touches `window.cultwatch`.
  html = html.replace('<script src="tinybuild.js"></script>',
    '<script src="js/cultwatch-core.js"></script>\n' +
    '    <script src="js/bootstrap.js"></script>\n' +
    '    <script src="tinybuild.js"></script>');

  fs.writeFileSync(path.join(www, 'index.html'), html);
  return RENDERER_FILES.length + 2;
}

if (require.main === module) {
  const r = build();
  const n = assets();
  console.log(`  bundled ${r.count} modules -> mobile/www/js/cultwatch-core.js (${Math.round(r.bytes / 1024)} KB)`);
  console.log(`  copied ${n} web assets -> mobile/www/`);
  console.log('  ' + r.ids.join(', '));
}

module.exports = { build, assets };
